### ISSUE TITLE
Add Cavatica CORS policy

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-api-bucketservice#25]
See: https://docs.sevenbridges.com/docs/enabling-cross-origin-resource-sharing-cors

This will allow easy display of various types of reports generated by the bix team in place of the Cavatica platform versus downloading, improving the user experience. The Marazita specifically asked for this capabilities. 

This requires trust on the Cavatica side, which is already done due to the IAM read policies in place. This policy is already in place for the `*seq*` buckets. I will triple check this before we move forward on automating across all buckets.

**Comment by allisonheath** [comment]
We're ok to move forward on automating this for our study buckets from now on.

**Comment by dankolbman** [comment]
Updated all prod study buckets with the new CORs rules in #29
