### ISSUE TITLE
Add no-delete policy

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-bucketservice#26]
Study buckets should have a no-delete policy so that users do not accidentally remove data.

**Comment by alubneuski** [comment]
Here is the delete policy:
resource aws_s3_bucket_policy "kf-seq-data-stjude-bucket" {
  bucket = "${aws_s3_bucket.kf-seq-data-stjude-bucket.id}"
  policy = <<EOF
{
      "Version": "2012-10-17",
      "Id": "kfSeqDataBroadPolicy",
      "Statement": [
          {
              "Sid": "DenyDeleteObjectAndBucket",
              "Effect": "Deny",
              "Principal": "*",
              "Action": [
                "s3:DeleteObjectTagging",
                "s3:DeleteObjectVersionTagging",
                "s3:DeleteObjectVersion",
                "s3:DeleteObject"
              ],
              "Resource": "arn:aws:s3:::<bucket name>/*"
          },
          {
              "Sid": "DenyDeleteObjectAndBucket",
              "Effect": "Deny",
              "Principal": "*",
              "Action": [
                "s3:DeleteBucket"
              ],
              "Resource": "arn:aws:s3:::<bucket name>"
          }
      ]
}
EOF
}

**Comment by dankolbman** [comment]
Added policy from #27 to all prod study buckets and replicated buckets.
